import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../../design_system/widgets/app_back_button.dart';
import '../../core/novel_source_capability.dart';
import 'book_source_diagnostic_models.dart';
import 'book_source_diagnostic_runner.dart';
import 'book_source_model.dart';

class BookSourceDiagnosticPage extends StatefulWidget {
  const BookSourceDiagnosticPage({
    super.key,
    required this.source,
    this.initialKeyword = '斗罗',
  });

  final BookSourceModel source;
  final String initialKeyword;

  @override
  State<BookSourceDiagnosticPage> createState() =>
      _BookSourceDiagnosticPageState();
}

class _BookSourceDiagnosticPageState extends State<BookSourceDiagnosticPage> {
  late final TextEditingController _keywordController;
  late final BookSourceDiagnosticRunner _runner;

  bool _running = false;
  String _runtimeError = '';
  RuntimeDiagnosticResult? _runtimeResult;
  Map<String, dynamic>? _staticResult;

  @override
  void initState() {
    super.initState();
    _keywordController = TextEditingController(text: widget.initialKeyword);
    _runner = BookSourceDiagnosticRunner(widget.source);

    WidgetsBinding.instance.addPostFrameCallback((_) {
      _runDiagnostic();
    });
  }

  @override
  void dispose() {
    _keywordController.dispose();
    super.dispose();
  }

  Future<void> _runDiagnostic() async {
    final keyword = _keywordController.text.trim().isEmpty
        ? '斗罗'
        : _keywordController.text.trim();

    setState(() {
      _running = true;
      _runtimeError = '';
    });

    try {
      _staticResult = await _runner.runStaticAnalysis();
      _runtimeResult = await _runner.runRuntimeDiagnostic(keyword: keyword);
    } catch (e) {
      _runtimeError = '诊断失败：$e';
    }

    if (mounted) {
      setState(() => _running = false);
    }
  }

  /// 截断超长字段，避免单个值（如几百行的发现菜单数组）挤爆剪贴板报告。
  /// 保留头部并标注省略字符数，便于判断是否为超长配置。
  static String _abbrev(String value, int max) {
    final one = value.replaceAll(RegExp(r'\s+'), ' ').trim();
    if (one.length <= max) return one;
    return '${one.substring(0, max)}…(共 ${one.length} 字符，已截断)';
  }

  Future<void> _copyReport() async {
    if (_runtimeResult == null) return;
    final buf = StringBuffer()
      ..writeln('📋 书源诊断报告')
      ..writeln('═══════════════════')
      ..writeln()
      ..writeln('📌 书源信息')
      ..writeln(
        '书源名：${_staticResult?['bookSourceName'] ?? widget.source.bookSourceName}',
      )
      ..writeln(
        '书源地址：${_staticResult?['bookSourceUrl'] ?? widget.source.bookSourceUrl}',
      )
      ..writeln(
        '书源分组：${_staticResult?['bookSourceGroup'] ?? widget.source.bookSourceGroup}',
      )
      ..writeln(
        '启用状态：${(_staticResult?['enabled'] ?? widget.source.enabled) ? '✅ 已启用' : '⛔ 已停用'}',
      )
      ..writeln(
        '搜索地址：${_staticResult?['searchUrl'] ?? widget.source.searchUrl}',
      )
      // 发现地址常是几百行的菜单数组（男/女频榜单+分类），整段贴出来会把
      // 后面真正用于排查的规则段挤出剪贴板，因此这里截断。
      ..writeln(
        '发现地址：${_abbrev(_staticResult?['exploreUrl'] ?? widget.source.exploreUrl, 160)}',
      )
      ..writeln();

    // 规则明细：只打印 key 名不足以排查（看不出 tocUrl 指向哪、chapterList
    // 是什么路径），所以连值一起输出，单值过长再截断。
    for (final label in [
      ('搜索规则', 'ruleSearch'),
      ('发现规则', 'ruleExplore'),
      ('详情规则', 'ruleBookInfo'),
      ('目录规则', 'ruleToc'),
      ('正文规则', 'ruleContent'),
    ]) {
      final rule = _staticResult?[label.$2] as Map<String, dynamic>?;
      if (rule != null && rule.isNotEmpty) {
        buf.writeln('${label.$1}:');
        for (final entry in rule.entries) {
          buf.writeln('  ${entry.key} = ${_abbrev('${entry.value}', 200)}');
        }
      } else {
        buf.writeln('${label.$1}: (空)');
      }
    }

    buf.writeln();
    buf.writeln(_runtimeResult!.briefReport);
    buf.writeln();

    for (final step in _runtimeResult!.steps) {
      final icon = switch (step.state) {
        RuntimeDiagnosticStepState.success => '✅',
        RuntimeDiagnosticStepState.warning => '⚠️',
        RuntimeDiagnosticStepState.failure => '❌',
        RuntimeDiagnosticStepState.skipped => '⏭️',
        RuntimeDiagnosticStepState.pending => '⏳',
        RuntimeDiagnosticStepState.running => '🔄',
      };
      buf.writeln('$icon ${step.title}');
      if (step.detail.isNotEmpty) {
        for (final line in step.detail.split('\n')) {
          buf.writeln('   $line');
        }
      }
      buf.writeln();
    }

    buf.writeln('═══════════════════');
    buf.writeln('Generated by Geek工具箱 Pro · Book Source Diagnostic');

    await Clipboard.setData(ClipboardData(text: buf.toString()));
    if (!mounted) return;
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(const SnackBar(content: Text('诊断报告已复制到剪贴板')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('书源诊断 - ${widget.source.bookSourceName}'),
        leading: AppBackButton(onPressed: () => Navigator.pop(context)),
        actions: [
          if (_runtimeResult != null)
            IconButton(
              icon: const Icon(Icons.copy_rounded),
              tooltip: '复制报告',
              onPressed: _copyReport,
            ),
        ],
      ),
      body: _buildBody(),
    );
  }

  Widget _buildBody() {
    if (_running) {
      return const Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 16),
            Text('正在诊断…', style: TextStyle(color: Colors.black54)),
          ],
        ),
      );
    }

    if (_runtimeError.isNotEmpty) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.error_outline, size: 48, color: Colors.red),
              const SizedBox(height: 12),
              Text(_runtimeError, textAlign: TextAlign.center),
              const SizedBox(height: 16),
              ElevatedButton.icon(
                onPressed: _runDiagnostic,
                icon: const Icon(Icons.refresh),
                label: const Text('重试'),
              ),
            ],
          ),
        ),
      );
    }

    if (_runtimeResult == null) {
      return const SizedBox.shrink();
    }

    return ListView(
      padding: const EdgeInsets.fromLTRB(16, 8, 16, 32),
      children: [
        _buildSourceCard(),
        _buildInputCard(),
        _buildStaticSummaryCard(),
        _buildRuntimeSummaryCard(_runtimeResult!),
        ...List.generate(
          _runtimeResult!.steps.length,
          (i) => _buildStepCard(_runtimeResult!.steps[i], i),
        ),
        _buildReportSection(),
      ],
    );
  }

  Widget _buildSourceCard() {
    final status =
        (_staticResult?['enabled'] as bool? ?? widget.source.enabled);
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(
                    _staticResult?['bookSourceName'] ??
                        widget.source.bookSourceName,
                    style: const TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 10,
                    vertical: 4,
                  ),
                  decoration: BoxDecoration(
                    color: status ? Colors.green.shade50 : Colors.grey.shade100,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    status ? '已启用' : '已停用',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: status
                          ? Colors.green.shade700
                          : Colors.grey.shade600,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            _metaRow('站点', _staticResult?['bookSourceUrl'] ?? '-'),
            _metaRow('分组', _staticResult?['bookSourceGroup'] ?? '-'),
            _metaRow('书源 ID', widget.source.id),
          ],
        ),
      ),
    );
  }

  Widget _metaRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(top: 4),
      child: Row(
        children: [
          SizedBox(
            width: 60,
            child: Text(
              label,
              style: const TextStyle(fontSize: 12, color: Colors.black54),
            ),
          ),
          Expanded(child: Text(value, style: const TextStyle(fontSize: 13))),
        ],
      ),
    );
  }

  Widget _buildInputCard() {
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('搜索关键词', style: TextStyle(fontWeight: FontWeight.w600)),
            const SizedBox(height: 8),
            TextField(
              controller: _keywordController,
              decoration: const InputDecoration(
                hintText: '输入搜索关键词',
                border: OutlineInputBorder(),
                contentPadding: EdgeInsets.symmetric(
                  horizontal: 12,
                  vertical: 10,
                ),
              ),
              onSubmitted: (_) => _runDiagnostic(),
            ),
            const SizedBox(height: 8),
            Align(
              alignment: Alignment.centerRight,
              child: ElevatedButton.icon(
                onPressed: _runDiagnostic,
                icon: const Icon(Icons.refresh, size: 18),
                label: const Text('重新诊断'),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStaticSummaryCard() {
    final report = _staticResult?['report'] as NovelSourceCapabilityReport?;
    if (report == null) return const SizedBox.shrink();

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Text(
                  '静态分析',
                  style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
                ),
                const SizedBox(width: 8),
                _statusBadge(
                  report.statusLabel,
                  _statusColor(report.statusLabel),
                ),
              ],
            ),
            const SizedBox(height: 8),
            _metaRow('适配器', report.adapterLabel),
            _metaRow('基础地址', report.baseUrl),
            if (report.matchedSignals.isNotEmpty) ...[
              const SizedBox(height: 4),
              const Text(
                '匹配信号',
                style: TextStyle(fontSize: 11, color: Colors.black45),
              ),
              for (final s in report.matchedSignals)
                Text(
                  '  · $s',
                  style: const TextStyle(fontSize: 11, color: Colors.black54),
                ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildRuntimeSummaryCard(RuntimeDiagnosticResult result) {
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              '运行时诊断',
              style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              runSpacing: 4,
              children: [
                _summaryChip('共 ${result.steps.length} 步', Colors.blue),
                _summaryChip('✅ ${result.successCount}', Colors.green),
                if (result.warningCount > 0)
                  _summaryChip('⚠️ ${result.warningCount}', Colors.orange),
                if (result.failureCount > 0)
                  _summaryChip('❌ ${result.failureCount}', Colors.red),
                if (result.skippedCount > 0)
                  _summaryChip('⏭️ ${result.skippedCount}', Colors.grey),
              ],
            ),
            const SizedBox(height: 6),
            Text(
              '耗时: ${result.elapsedSeconds}s · 关键词: "${result.keyword}"',
              style: const TextStyle(fontSize: 12, color: Colors.black54),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStepCard(RuntimeDiagnosticStep step, int index) {
    final icon = switch (step.state) {
      RuntimeDiagnosticStepState.success => '✅',
      RuntimeDiagnosticStepState.warning => '⚠️',
      RuntimeDiagnosticStepState.failure => '❌',
      RuntimeDiagnosticStepState.skipped => '⏭️',
      RuntimeDiagnosticStepState.pending => '⏳',
      RuntimeDiagnosticStepState.running => '🔄',
    };
    final borderColor = switch (step.state) {
      RuntimeDiagnosticStepState.success => Colors.green.shade200,
      RuntimeDiagnosticStepState.warning => Colors.orange.shade200,
      RuntimeDiagnosticStepState.failure => Colors.red.shade200,
      _ => Colors.grey.shade200,
    };

    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(color: borderColor, width: 1),
      ),
      child: ExpansionTile(
        tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
        leading: Text(icon, style: const TextStyle(fontSize: 20)),
        title: Text(
          step.title,
          style: const TextStyle(fontWeight: FontWeight.w600),
        ),
        subtitle: Text(
          step.summary,
          style: const TextStyle(fontSize: 12),
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
        trailing: step.durationMs > 0
            ? Text(
                '${step.durationMs}ms',
                style: TextStyle(fontSize: 11, color: Colors.grey.shade600),
              )
            : null,
        children: [
          if (step.detail.isNotEmpty)
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
              child: SelectableText(
                step.detail,
                style: const TextStyle(
                  fontSize: 12,
                  height: 1.5,
                  color: Colors.black87,
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildReportSection() {
    return Padding(
      padding: const EdgeInsets.only(top: 8),
      child: SizedBox(
        width: double.infinity,
        child: OutlinedButton.icon(
          onPressed: _copyReport,
          icon: const Icon(Icons.copy_rounded),
          label: const Text('复制完整诊断报告'),
        ),
      ),
    );
  }

  Widget _statusBadge(String label, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: color.withValues(alpha: 0.3)),
      ),
      child: Text(
        label,
        style: TextStyle(
          fontSize: 11,
          color: color,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Color _statusColor(String label) {
    if (label.contains('可用') ||
        label.contains('就绪') ||
        label.contains('ready')) {
      return Colors.green;
    }
    if (label.contains('受限') || label.contains('limited')) {
      return Colors.orange;
    }
    return Colors.red;
  }

  Widget _summaryChip(String label, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(
        label,
        style: TextStyle(
          fontSize: 12,
          color: color,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }
}
